export const environment = {
  production: true,
  EMAILJS_SERVICE_ID: '<EMAILJS_SERVICE_ID>',
  EMAILJS_TEMPLATE_ID: '<EMAILJS_TEMPLATE_ID>',
  EMAILJS_AUTO_REPLY_TEMPLATE_ID: '<EMAILJS_AUTO_REPLY_TEMPLATE_ID>',
  EMAILJS_PUBLIC_KEY: '<EMAILJS_PUBLIC_KEY>',
  GOOGLE_ANALYTICS_ID: '<GOOGLE_ANALYTICS_ID>',

  OPEN_WEATHER_API_KEY: '<OPENWEATHER_API_KEY>',
  OPEN_WEATHER_API_URL: '<OPENWEATHER_API_URL>'
};
